#pragma once
#define GAME_API_BASE 100

enum game_api_ids
{
	ECALL_SELF_TEST = GAME_API_BASE,
	// Game Engine
	ECALL_ASSERT_FAIL,
	ECALL_WRITE,
	ECALL_MEASURE,
	ECALL_FARCALL,
	ECALL_INTERRUPT,
	ECALL_MACHINE_HASH,
	ECALL_EACH_FRAME,
	ECALL_CHECK_GROUP,
	ECALL_GAME_EXIT,
	// Math
	ECALL_SINF,
	ECALL_RANDF,
	ECALL_SMOOTHSTEP,
	ECALL_VEC_LENGTH,
	ECALL_VEC_ROTATE,
	ECALL_VEC_NORMALIZE,

	ECALL_LAST
};


#define REASON_FRAME         10
#define REASON_CAMERA_DOLLY  12
#define REASON_DIALOGUE      22

// Configurable location of function groups
#define FUNCTION_GROUP_AREA  0xFF000000

#define GROUP_TIMERS 2
