#pragma once
#define GAME_API_BASE 500

enum game_api_ids
{
	ECALL_SELF_TEST = GAME_API_BASE,
	// Game Engine
	ECALL_ASSERT_FAIL,
	ECALL_WRITE,
	ECALL_MEASURE,
	ECALL_DYNCALL,
	ECALL_FARCALL,
	ECALL_FARCALL_DIRECT,
	ECALL_INTERRUPT,
	ECALL_MACHINE_HASH,
	ECALL_EACH_FRAME,
	ECALL_MULTIPROCESS,
	ECALL_MULTIPROCESS_FORK,
	ECALL_MULTIPROCESS_WAIT,
	ECALL_GAME_EXIT,
	// Math
	ECALL_SINF,
	ECALL_RANDF,
	ECALL_SMOOTHSTEP,
	ECALL_VEC_LENGTH,
	ECALL_VEC_ROTATE,
	ECALL_VEC_NORMALIZE,

	ECALL_LAST
};


#define REASON_FRAME         10
#define REASON_CAMERA_DOLLY  12
#define REASON_DIALOGUE      22
